provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  hello-openfaas:
    lang: python3-arm64
    handler: ./hello-openfaas
    image: desaegher/hello-openfaas
    environment:
      content_type: text/html

